export type PhoneCountryDefinition = {
  iso2: string;
  dialCode: string;
};

/** Dial codes for international phone input (ISO 3166-1 alpha-2). */
export const PHONE_COUNTRY_DEFINITIONS: PhoneCountryDefinition[] = [
  { iso2: "TR", dialCode: "90" },
  { iso2: "DE", dialCode: "49" },
  { iso2: "GB", dialCode: "44" },
  { iso2: "RU", dialCode: "7" },
  { iso2: "US", dialCode: "1" },
  { iso2: "FR", dialCode: "33" },
  { iso2: "NL", dialCode: "31" },
  { iso2: "BE", dialCode: "32" },
  { iso2: "AT", dialCode: "43" },
  { iso2: "CH", dialCode: "41" },
  { iso2: "IT", dialCode: "39" },
  { iso2: "ES", dialCode: "34" },
  { iso2: "SA", dialCode: "966" },
  { iso2: "AE", dialCode: "971" },
  { iso2: "QA", dialCode: "974" },
  { iso2: "KW", dialCode: "965" },
  { iso2: "BH", dialCode: "973" },
  { iso2: "OM", dialCode: "968" },
  { iso2: "UA", dialCode: "380" },
  { iso2: "KZ", dialCode: "7" },
  { iso2: "AZ", dialCode: "994" },
  { iso2: "GE", dialCode: "995" },
  { iso2: "IQ", dialCode: "964" },
  { iso2: "IR", dialCode: "98" },
  { iso2: "IL", dialCode: "972" },
  { iso2: "EG", dialCode: "20" },
  { iso2: "GR", dialCode: "30" },
  { iso2: "BG", dialCode: "359" },
  { iso2: "RO", dialCode: "40" },
  { iso2: "PL", dialCode: "48" },
  { iso2: "CZ", dialCode: "420" },
  { iso2: "HU", dialCode: "36" },
  { iso2: "SE", dialCode: "46" },
  { iso2: "NO", dialCode: "47" },
  { iso2: "DK", dialCode: "45" },
  { iso2: "FI", dialCode: "358" },
  { iso2: "IE", dialCode: "353" },
  { iso2: "PT", dialCode: "351" },
  { iso2: "LU", dialCode: "352" },
  { iso2: "RS", dialCode: "381" },
  { iso2: "HR", dialCode: "385" },
  { iso2: "BA", dialCode: "387" },
  { iso2: "MK", dialCode: "389" },
  { iso2: "AL", dialCode: "355" },
  { iso2: "CY", dialCode: "357" },
  { iso2: "MT", dialCode: "356" },
  { iso2: "IN", dialCode: "91" },
  { iso2: "PK", dialCode: "92" },
  { iso2: "CN", dialCode: "86" },
  { iso2: "JP", dialCode: "81" },
  { iso2: "KR", dialCode: "82" },
  { iso2: "AU", dialCode: "61" },
  { iso2: "CA", dialCode: "1" },
  { iso2: "BR", dialCode: "55" },
  { iso2: "MX", dialCode: "52" },
  { iso2: "AR", dialCode: "54" },
  { iso2: "ZA", dialCode: "27" },
  { iso2: "NG", dialCode: "234" },
  { iso2: "MA", dialCode: "212" },
  { iso2: "TN", dialCode: "216" },
  { iso2: "LY", dialCode: "218" },
  { iso2: "UZ", dialCode: "998" },
  { iso2: "TM", dialCode: "993" },
  { iso2: "KG", dialCode: "996" },
  { iso2: "TJ", dialCode: "992" },
  { iso2: "AM", dialCode: "374" },
  { iso2: "MD", dialCode: "373" },
  { iso2: "BY", dialCode: "375" },
  { iso2: "LT", dialCode: "370" },
  { iso2: "LV", dialCode: "371" },
  { iso2: "EE", dialCode: "372" },
  { iso2: "SK", dialCode: "421" },
  { iso2: "SI", dialCode: "386" },
  { iso2: "ME", dialCode: "382" },
  { iso2: "XK", dialCode: "383" },
];

export const DEFAULT_PHONE_COUNTRY_CODE = "TR";

export const PHONE_COUNTRY_PRIORITY = [
  "TR",
  "DE",
  "GB",
  "RU",
  "US",
  "FR",
  "NL",
  "SA",
  "AE",
  "IT",
  "ES",
  "AT",
  "CH",
  "BE",
  "UA",
  "KZ",
  "AZ",
] as const;

export function getPhoneCountryByIso2(
  iso2: string,
): PhoneCountryDefinition | undefined {
  return PHONE_COUNTRY_DEFINITIONS.find(
    (country) => country.iso2 === iso2.toUpperCase(),
  );
}
